[package]
name = "sudoku"
version = "0.1.0"
authors = ["Henry Denny <henry.denny12@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.21.0" }
